version: '3'
services:
  mysql-standalone:
    image: 'mysql:5.7'
    environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_PASSWORD=root
       - MYSQL_DATABASE=testdb
    ports:
      - "3307:3306"
  employee-service-container:
    image: 'employee-service'
    ports:
      - "8200:8200"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/testdb?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: "./"
      dockerfile: "DockerFile"
    depends_on:
      - mysql-standalone